# Generated by Django 5.2 on 2025-05-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='gear_type',
            field=models.CharField(choices=[('weapon', 'Weapon'), ('armor', 'Armor'), ('accessory', 'Accessory')], default='weapon', max_length=50),
        ),
    ]
