# Generated by Django 5.2 on 2025-05-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_gear_gear_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='money_bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gear',
            name='time_bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gear',
            name='xp_bonus',
            field=models.FloatField(default=0.0),
        ),
    ]
