# Generated by Django 5.2 on 2025-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_currentadventure_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentadventure',
            name='time_started',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
