# Generated by Django 5.2 on 2025-04-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_currentadventure_time_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='money',
            field=models.BigIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='xp',
            field=models.BigIntegerField(default=0),
        ),
    ]
