# Generated by Django 5.2 on 2025-05-03 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_owneditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owneditem',
            name='item_id',
        ),
    ]
