# Generated by Django 5.2 on 2025-05-03 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
        ('users', '0007_remove_owneditem_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='owneditem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.gear'),
        ),
    ]
