# Generated by Django 5.2 on 2025-05-03 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
        ('users', '0008_owneditem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owneditem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gear.gear'),
        ),
    ]
