# Generated by Django 5.2 on 2025-04-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle', models.BooleanField(default=True)),
                ('required_level', models.IntegerField(default=1)),
                ('time_to_complete', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reward_min', models.IntegerField(default=0)),
                ('reward_max', models.IntegerField(default=0)),
                ('xp_min', models.IntegerField(default=0)),
                ('xp_max', models.IntegerField(default=0)),
            ],
        ),
    ]
