# Generated by Django 5.2 on 2025-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='reward_max',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='reward_min',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='time_to_complete',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='xp_max',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='xp_min',
            field=models.BigIntegerField(default=0),
        ),
    ]
